apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: null
  name: amqp-ssl
spec:
  host: amqp-ssl-amq-demo.127.0.0.1.nip.io
  tls:
    termination: passthrough
  to:
    kind: Service
    name: amq-broker-amq-amqp-ssl
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
